#!/bin/bash
# ============================================================
#  Mission Control — Installer
#  Run from the extracted zip directory:  bash install.sh
# ============================================================
set -euo pipefail

# ── Colors ───────────────────────────────────────────────────
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; BOLD='\033[1m'; NC='\033[0m'

ok()   { echo -e "${GREEN}✓${NC}  $*"; }
warn() { echo -e "${YELLOW}⚠${NC}  $*"; }
err()  { echo -e "${RED}✗${NC}  $*" >&2; }
hdr()  { echo -e "\n${CYAN}${BOLD}── $* ──${NC}"; }
ask()  { echo -en "${BOLD}$*${NC} "; }

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_FILE="$INSTALL_DIR/install.log"
exec > >(tee -a "$LOG_FILE") 2>&1

# ── Banner ───────────────────────────────────────────────────
echo ""
echo -e "${CYAN}${BOLD}"
echo "  ╔══════════════════════════════════════════╗"
echo "  ║       Mission Control — Installer        ║"
echo "  ║      AI Agent Management Dashboard       ║"
echo "  ╚══════════════════════════════════════════╝"
echo -e "${NC}"

# ── Prerequisite checks ──────────────────────────────────────
hdr "Checking prerequisites"

# Node.js ≥ 18
if ! command -v node &>/dev/null; then
  err "Node.js not found. Install Node.js 18+ first: https://nodejs.org"
  exit 1
fi
NODE_VER=$(node -e "process.stdout.write(process.version.replace('v',''))")
NODE_MAJ="${NODE_VER%%.*}"
if (( NODE_MAJ < 18 )); then
  err "Node.js $NODE_VER found but 18+ is required."
  exit 1
fi
ok "Node.js v$NODE_VER"

# npm
if ! command -v npm &>/dev/null; then
  err "npm not found."
  exit 1
fi
ok "npm $(npm -v)"

# pm2 (optional but recommended)
HAS_PM2=false
if command -v pm2 &>/dev/null; then
  HAS_PM2=true
  ok "pm2 $(pm2 -v) (process manager)"
else
  warn "pm2 not found — will provide cron-based keep-alive instructions."
  warn "Install pm2 globally with: npm install -g pm2"
fi

# ── Collect configuration ────────────────────────────────────
hdr "Configuration"

echo ""
echo "Press ENTER to accept defaults shown in [brackets]."
echo ""

# Domain / install path
DEFAULT_DOMAIN=$(basename "$INSTALL_DIR")
ask "Public domain for this install (e.g. mc.yourdomain.com) [$DEFAULT_DOMAIN]:"
read -r INPUT_DOMAIN
DOMAIN="${INPUT_DOMAIN:-$DEFAULT_DOMAIN}"

# Port — find a free one starting at 5000
find_free_port() {
  local port=$1
  while ss -tln 2>/dev/null | grep -q ":$port " || \
        netstat -tln 2>/dev/null | grep -q ":$port "; do
    port=$((port + 1))
  done
  echo "$port"
}
DEFAULT_PORT=$(find_free_port 5000)
ask "Port for Node.js to listen on [$DEFAULT_PORT]:"
read -r INPUT_PORT
PORT="${INPUT_PORT:-$DEFAULT_PORT}"

# Database
echo ""
echo -e "${YELLOW}Database connection${NC} (MariaDB / MySQL — must exist already):"
ask "  DB host [localhost]:"
read -r DB_HOST; DB_HOST="${DB_HOST:-localhost}"

ask "  DB port [3306]:"
read -r DB_PORT; DB_PORT="${DB_PORT:-3306}"

ask "  DB name:"
read -r DB_NAME
while [[ -z "$DB_NAME" ]]; do
  warn "DB name is required."
  ask "  DB name:"
  read -r DB_NAME
done

ask "  DB user:"
read -r DB_USER
while [[ -z "$DB_USER" ]]; do
  warn "DB user is required."
  ask "  DB user:"
  read -r DB_USER
done

ask "  DB password:"
read -rs DB_PASSWORD; echo ""
while [[ -z "$DB_PASSWORD" ]]; do
  warn "DB password is required."
  ask "  DB password:"
  read -rs DB_PASSWORD; echo ""
done

# Session secret — auto-generate if not provided
DEFAULT_SECRET=$(node -e "require('crypto').randomBytes(32).toString('hex').then ? '' : process.stdout.write(require('crypto').randomBytes(32).toString('hex'))" 2>/dev/null || \
  cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1 || \
  date | md5sum | awk '{print $1}')
ask "Session secret [auto-generated]:"
read -r INPUT_SECRET
SESSION_SECRET="${INPUT_SECRET:-$DEFAULT_SECRET}"

# HTTPS flag
ask "Is this install served over HTTPS? (y/N):"
read -r INPUT_HTTPS
HTTPS_FLAG="false"
[[ "$INPUT_HTTPS" =~ ^[Yy] ]] && HTTPS_FLAG="true"

# GitHub repo (for the update button in Settings)
DEFAULT_REPO="chad-1964/mission-control"
ask "GitHub repo for updates [$DEFAULT_REPO]:"
read -r INPUT_REPO
GH_REPO="${INPUT_REPO:-$DEFAULT_REPO}"

# ── Write .env ───────────────────────────────────────────────
hdr "Writing configuration"

ENV_FILE="$INSTALL_DIR/.env"
cat > "$ENV_FILE" <<ENVEOF
# Mission Control — Environment
# Generated by install.sh on $(date)

NODE_ENV=production
PORT=$PORT
HTTPS=$HTTPS_FLAG

# Database
DB_HOST=$DB_HOST
DB_PORT=$DB_PORT
DB_NAME=$DB_NAME
DB_USER=$DB_USER
DB_PASSWORD=$DB_PASSWORD

# Session
SESSION_SECRET=$SESSION_SECRET

# GitHub repo (used by Settings → System for update checks)
GITHUB_REPO=$GH_REPO
ENVEOF

ok ".env written to $ENV_FILE"

# ── Install dependencies ─────────────────────────────────────
hdr "Installing dependencies"
cd "$INSTALL_DIR"
npm install --omit=dev --no-fund --no-audit 2>&1 | tail -3
ok "npm install complete"

# ── Database migration ───────────────────────────────────────
hdr "Running database migration"
npm run migrate
ok "Database ready"

# ── Build ────────────────────────────────────────────────────
hdr "Building application"
npm run build
ok "Build complete → dist/index.cjs"

# ── Process management ───────────────────────────────────────
hdr "Setting up process manager"

PM2_NAME="mc-${DOMAIN//[^a-zA-Z0-9]/-}"

if $HAS_PM2; then
  # Stop existing instance with this name if running
  pm2 delete "$PM2_NAME" 2>/dev/null || true

  pm2 start dist/index.cjs \
    --name "$PM2_NAME" \
    --env production \
    -- 2>/dev/null || \
  pm2 start dist/index.cjs --name "$PM2_NAME"

  pm2 save
  ok "PM2 process '$PM2_NAME' started and saved"
  USING_PM2=true
else
  # Start with nohup as fallback
  mkdir -p "$INSTALL_DIR/logs"
  nohup node dist/index.cjs >> "$INSTALL_DIR/logs/mc.log" 2>&1 &
  echo $! > "$INSTALL_DIR/mc.pid"
  ok "Node.js started (PID $(cat "$INSTALL_DIR/mc.pid")) — logs at logs/mc.log"
  USING_PM2=false
fi

# ── .htaccess proxy ──────────────────────────────────────────
hdr "Configuring Apache reverse proxy (.htaccess)"

HTACCESS="$INSTALL_DIR/.htaccess"
HTACCESS_BLOCK="# ── Mission Control proxy (port $PORT) ──
<IfModule mod_rewrite.c>
  RewriteEngine On
  RewriteRule ^$ http://127.0.0.1:$PORT/ [P,L]
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteRule ^(.*)$ http://127.0.0.1:$PORT/\$1 [P,L]
</IfModule>
<IfModule mod_proxy.c>
  ProxyPassReverse / http://127.0.0.1:$PORT/
</IfModule>"

if [[ -f "$HTACCESS" ]]; then
  if grep -q "127.0.0.1:$PORT" "$HTACCESS" 2>/dev/null; then
    ok ".htaccess already contains proxy rule for port $PORT — no change needed"
  elif grep -q "Mission Control proxy" "$HTACCESS" 2>/dev/null; then
    # Update existing MC block with new port
    # Remove the old block and append the new one
    TMPFILE=$(mktemp)
    sed '/# ── Mission Control proxy/,/ProxyPassReverse/d' "$HTACCESS" > "$TMPFILE"
    echo "" >> "$TMPFILE"
    echo "$HTACCESS_BLOCK" >> "$TMPFILE"
    mv "$TMPFILE" "$HTACCESS"
    ok ".htaccess updated with new port $PORT"
  else
    # Append to existing .htaccess
    echo "" >> "$HTACCESS"
    echo "$HTACCESS_BLOCK" >> "$HTACCESS"
    ok ".htaccess updated (appended proxy rules for port $PORT)"
  fi
else
  echo "$HTACCESS_BLOCK" > "$HTACCESS"
  ok ".htaccess created with proxy rules for port $PORT"
fi

# ── Summary ──────────────────────────────────────────────────
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════╗"
echo -e "║        Mission Control is installed!         ║"
echo -e "╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}URL:${NC}      https://$DOMAIN  (or http if no SSL)"
echo -e "  ${BOLD}Port:${NC}     $PORT"
echo -e "  ${BOLD}App dir:${NC}  $INSTALL_DIR"
echo -e "  ${BOLD}Log:${NC}      $LOG_FILE"
echo ""

# ── Cron strings ─────────────────────────────────────────────
echo -e "${CYAN}${BOLD}── Cron / Startup Strings ──────────────────────────────────${NC}"
echo ""
echo "Copy these into cPanel → Cron Jobs if your host doesn't auto-start Node:"
echo ""

if $USING_PM2; then
  echo -e "${BOLD}Startup (runs pm2 resurrect after server reboot):${NC}"
  echo "  @reboot sleep 20 && $(which pm2) resurrect"
  echo ""
  echo -e "${BOLD}Health watchdog (restarts if crashed, runs every 5 min):${NC}"
  echo "  */5 * * * * $(which pm2) list | grep -q '$PM2_NAME.*online' || (cd $INSTALL_DIR && $(which pm2) start dist/index.cjs --name $PM2_NAME)"
else
  echo -e "${BOLD}Startup (starts app after server reboot):${NC}"
  echo "  @reboot sleep 20 && cd $INSTALL_DIR && nohup node dist/index.cjs >> $INSTALL_DIR/logs/mc.log 2>&1 &"
  echo ""
  echo -e "${BOLD}Health watchdog (restarts if not running, every 5 min):${NC}"
  echo "  */5 * * * * pgrep -f 'node.*$INSTALL_DIR/dist/index.cjs' || (cd $INSTALL_DIR && nohup node dist/index.cjs >> $INSTALL_DIR/logs/mc.log 2>&1 &)"
fi

echo ""
echo -e "${CYAN}${BOLD}── If Apache proxy isn't working ────────────────────────────${NC}"
echo ""
echo "The installer wrote an .htaccess at:"
echo "  $HTACCESS"
echo ""
echo "If the site still returns Apache's default page, ask your host to confirm:"
echo "  • mod_rewrite and mod_proxy are enabled for your account"
echo "  • AllowOverride All is set for the subdomain document root"
echo ""
echo "Alternatively, add this to your cPanel → Node.js App Manager:"
echo "  Application root: $INSTALL_DIR"
echo "  Application URL:  $DOMAIN"
echo "  Application startup file: dist/index.cjs"
echo ""
echo -e "${GREEN}${BOLD}Visit https://$DOMAIN to complete setup via the wizard.${NC}"
echo ""
